baseURL = "https://cofragemsilva.pt"
disableKinds = ["taxonomy", "term"]
languageCode = "pt-pt"
relativeURLs = "true"
theme = "hugo-now-ui"
title = "Cofragem e Armação de Ferro - Eduardo Silva"
[[menu.footer]]
identifier = "copyright"
name = "Copyright © {now_year}"
weight = 1
[[menu.footer]]
identifier = "footerHomeButton"
pre = "<i class='now-ui-icons arrows-1_minimal-up btn_round'></i>"
url = "#top"
weight = 3
[[menu.footer]]
identifier = "alvara"
name = "Alvará"
weight = 2
[[menu.main]]
name = "Sobre"
pre = "<i class='now-ui-icons business_badge'></i>"
url = "/#about_homepage"
weight = 3
[[menu.main]]
name = "Aluguer de Material"
parent = "dropdown"
url = "/servicos/aluguer-material/#aluguer_content"
weight = 7
[[menu.main]]
name = "Armação de Ferro"
parent = "dropdown"
url = "/servicos/armacao-ferro/#ferro_content"
weight = 5
[[menu.main]]
name = "Betonagem"
parent = "dropdown"
url = "/servicos/betonagem/#betonagem_content"
weight = 4
[[menu.main]]
name = "Cofragem"
parent = "dropdown"
url = "/servicos/cofragem/#cofragem_content"
weight = 1
[[menu.main]]
identifier = "dropdown"
name = "Serviços"
pre = "<i class='now-ui-icons loader_gear'></i>"
url = "/servicos"
weight = 6
[[menu.main]]
name = "Contactos"
pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
url = "/contactos"
weight = 9
[[menu.main]]
name = "Portfólio"
pre = "<i class='now-ui-icons media-1_album'></i>"
url = "/portfolio"
weight = 8
[[menu.main]]
name = "Página Inicial"
pre = "<i class='now-ui-icons business_bank'></i>"
url = "/"
weight = 2
[minify]
minifyOutput = false
[minify.tdewolff.html]
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = true
[minify.tdewolff.xml]
keepWhitespace = false
[params]
about_us_homepage_enable = true
about_us_homepage_title = "Sobre"
authorName = "Marco Silva"
custom_css = ["css/highlight.min.css"]
custom_js = []
date_format = "Mon, Jan 2, 2006"
default_header_background = "/media/headers/headerDefault.jpg"
description = "Eduardo Silva, empresário de construção civil, desenvolve a sua actividade principal nos sectores da cofragem e armação de ferro para estruturas de betão armado, em edifícios residenciais e não residenciais, na zona do Algarve."
highlightCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
highlightjsVersion = "9.10.0"
keywords = "construção civil, cofragem, cofragens, betonagem, betão, armação de ferro, aluguer, aluguel, material de cofragem, carvoeiro, portimão, lagoa, alvor, armação de pêra, lagos, ferragudo, algarve"
name = "Eduardo Silva"
tint = "orange"
[permalinks]
post = "/:year/:month/:day/:slug/"
