baseURL = "https://cofragemsilva.pt"
languageCode = "pt-pt"
theme = "hugo-now-ui"
title = "Cofragem Silva" #titulo que vai aparecer quando se pesquisa o site

relativeURLs = "true"

[[menu.footer]]
identifier = "copyright"
name = "Copyright © 2020"
weight = 1
[[menu.footer]]
identifier = "alvara"
name = "Alvará"
weight = 2
[[menu.footer]]
identifier = "footerHomeButton"
pre = "<i class='now-ui-icons arrows-1_minimal-up btn_round'></i>"
url = "#top"
weight = 3

[[menu.main]]
name = "Página Inicial"
pre = "<i class='now-ui-icons business_bank'></i>"
url = "/"
weight = 1
[[menu.main]]
name = "Sobre"
pre = "<i class='now-ui-icons business_badge'></i>"
url = "/#about_homepage"
weight = 2
[[menu.main]]
  name = "Serviços"
  pre = "<i class='now-ui-icons loader_gear'></i>"
  url = "/servicos"
  weight = 3
  identifier = "dropdown"
[[menu.main]]
    name = "Cofragem"
    #pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    url = "/servicos/cofragem/#cofragem_content"
    weight = 1
    parent = "dropdown"
[[menu.main]]
    name = "Betonagem"
    #pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    url = "/servicos/betonagem/#betonagem_content"
    weight = 2
    parent = "dropdown"
[[menu.main]]
    name = "Armação de Ferro"
    #pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    url = "/servicos/armacao-ferro/#ferro_content"
    weight = 3
    parent = "dropdown"
[[menu.main]]
    name = "Aluguer de Material"
    #pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    url = "/servicos/aluguer-material/#aluguer_content"
    weight = 4
    parent = "dropdown"
[[menu.main]]
name = "Portefólio"
pre = "<i class='now-ui-icons media-1_album'></i>"
url = "/portefolio"
weight = 5
[[menu.main]]
name = "Contactos"
pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
url = "/contactos"
weight = 6

[params]
custom_css = ["css/highlight.min.css"]
custom_js = []
date_format = "Mon, Jan 2, 2006"
highlightCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
highlightjsVersion = "9.10.0"
tint = "orange"
default_header_background = "../img/headers/headerObra.jpg"
#Main name in the website
name = "Eduardo Silva"
description = ""  #TODO #default meta description

#post does not even exist, but if this is helpfull create the permalink format for what this site uses
[permalinks]
post = "/:year/:month/:day/:slug/"


[minify]
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = true     #default false
    [minify.tdewolff.xml]
      keepWhitespace = false