baseURL = "https://cofragemsilva.pt/"
languageCode = "pt-pt"
title = "Cofragem Silva"
theme = "hugo-now-ui"



[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Página Inicial"
    url = "/"
    pre = "<i class='now-ui-icons business_bank'></i>"
    weight = 1
[[menu.main]]
    name = "Sobre"
    url = "/#about"
    pre = "<i class='now-ui-icons business_badge'></i>"
    weight = 2

[[menu.main]]
    name = "Serviços"
    url = "/#services"
    pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
    weight = 3

#[[menu.main]]
#    name = "Serviços"
#    pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
#    url = "#"
#    weight = 4
#    identifier = "dropdown"
#[[menu.main]]
#    name = "Todos"
#    url = "/servicos/"
#    weight = 1
#    parent = "dropdown"
#[[menu.main]]
#    name = "Cofragem"
#    pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
#    url = "/servicos/#cofragem"
#    weight = 2
#    parent = "dropdown"
#[[menu.main]]
#    name = "Armação de Ferro"
#    pre = "<i class='now-ui-icons text_align-center'></i>"
#    url = "/servicos/#ferro"
#    weight = 3
#    parent = "dropdown"
#[[menu.main]]
#    name = "Aluguer de Material"
#    pre = "<i class='now-ui-icons shopping_tag-content'></i>"
#    url = "/servicos/#aluguer"
#    weight = 4
#    parent = "dropdown"
    
[[menu.main]]
    name = "Portefólio"
    url = "/#portfolio"
    pre = "<i class='now-ui-icons media-1_album'></i>"
    weight = 5
[[menu.main]]
    name = "Contactos"
    pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
    url = "/contacts"
    weight = 6

[[menu.footer]]
    identifier = "footerHomeButton"
    pre = "<i class='now-ui-icons arrows-1_minimal-up'></i>"
    weight = 1
    url = "/"
# TODO perceber bem o que fazer devido a licensa
[[menu.footer]]
    identifier = "copyright"
    name = "Copyright © 2020"
    weight = 2

[[menu.footer]]
    identifier = "alvara"
    name = "Alvará"
    weight = 3

[[menu.footer]]
    identifier = "phone_number"
    pre = "<i class='now-ui-icons tech_mobile'></i>"
    name = "962757100"
    weight = 4

[[menu.footer]]
    identifier = "email"
    pre = "<i class='now-ui-icons ui-1_email-85'></i>"
    name = "cofragemsilva@hotmail.com"
    weight = 5

[params]
    name = "Eduardo Silva"
    # orange, red, yellow, blue, green
    #TODO which one to use
    tint = "orange"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    #TODO obras pastas enumeradas aqui e fotos nessas pastas tbm, dps no html é só fazer  range  atraves dessas pastas e fotos para as galerias