baseURL = "https://cofragemsilva.pt"
languageCode = "pt-pt"
theme = "hugo-now-ui"
title = "Cofragem Silva"

[[menu.footer]]
identifier = "footerHomeButton"
pre = "<i class='now-ui-icons arrows-1_minimal-up'></i>"
url = "/#home"
weight = 1
[[menu.footer]]
identifier = "copyright"
name = "Copyright © 2020"
weight = 2
[[menu.footer]]
identifier = "alvara"
name = "Alvará"
weight = 3
[[menu.footer]]
identifier = "phone_number"
name = "962757100"
pre = "<i class='now-ui-icons tech_mobile'></i>"
weight = 4
[[menu.footer]]
identifier = "email"
name = "cofragemsilva@hotmail.com"
pre = "<i class='now-ui-icons ui-1_email-85'></i>"
weight = 5

[[menu.main]]
name = "Página Inicial"
pre = "<i class='now-ui-icons business_bank'></i>"
url = "/"
weight = 1
[[menu.main]]
name = "Sobre"
pre = "<i class='now-ui-icons business_badge'></i>"
url = "/#about"
weight = 2
[[menu.main]]
name = "Serviços"
pre = "<i class='now-ui-icons ui-2_settings-90'></i>"
url = "/#services"
weight = 3
[[menu.main]]
name = "Portefólio"
pre = "<i class='now-ui-icons media-1_album'></i>"
url = "/#portfolio"
weight = 5
[[menu.main]]
name = "Contactos"
pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
url = "/contacts"
weight = 6

[params]
custom_css = ["css/highlight.min.css"]
custom_js = []
date_format = "Mon, Jan 2, 2006"
description = "A website built through Hugo and blogdown."
highlightCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
highlightjsVersion = "9.10.0"
tint = "orange"
#Main name in the website
name = "Eduardo Silva"

[permalinks]
post = "/:year/:month/:day/:slug/"
