---
label: Serviço
hide_body: true
fields:
- type: text
  name: title
  label: título
- type: text
  name: weight
  label: prioridade
- type: textarea
  name: description
  label: descrição
- type: image_gallery
  name: images
  label: imagens
- type: boolean
  name: homepage_link_enable
  label: homepage_link_enable
pages:
- content/servicos/cofragem.md
- content/servicos/betonagem.md
- content/servicos/ferro.md
- content/servicos/aluguer.md
